export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGOUT='LOGOUT';
export const GET_SENSOR='GET_SENSOR';
export const SENSOR_ERROR='SENSOR_ERROR';
export const UPDATE_SENSOR ='UPDATE_SENSOR'; 
export const CLEAR_SENSOR='CLEAR_SENSOR';
export const GET_GATEWAY='GET_GATEWAY';
export const GATEWAY_ERROR='GATEWAY_ERROR';
export const CLEAR_GATEWAY='CLEAR_GATEWAY';
export const UPDATE_GATEWAY ='UPDATE_GATEWAY'; 
export const SET_ALARM ='SET_ALARM'; 
export const GET_ALARM ='GET_ALARM'; 
export const ALARM_ERROR ='ALARM_ERROR'; 




